# This is a basic workflow to help you get started with Actions

name: CI


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: APIsec Trigger Scan
        # You may pin to the exact commit or the version.
        # uses: SyedsImran/NewDrone@3a4dc52369aaeb9f76cf568e78aeb08337d565e3
        uses: SyedsImran/NewDrone@v1.0.1
        with:
          # The APIsec username with which the scans will be executed
          apisec-username: ${{ secrets.apisec_username }}
          # The Password of the APIsec user with which the scans will be executed
          apisec-password: ${{ secrets.apisec_password }}
          # The Name of the project for security scan
          apisec-project: "testingapiproject"
          # The Name of the scan profile to be executed
          apisec-profile: "Master"
          # The location the scan will be executed in
          apisec-region: "Super_2"
          # The path to the sarif format result file
          sarif-result-file: "sarif"
          # The severity to verify like "Critical", "High" ..etc based on which to break pipeline
          apisec-severity: "High"
          # The threshold severity count of "Critical", "High" ..etc based on which to break pipeline
          apisec-threshold: 2
          # Whether to regenerate the playbooks, if yes pass value as "true" or else "false"
          apisec-playbook-regenerate: false
          # Whether to trigger scan email reports, if yes pass value as "true" or else "false"
          apisec-email-report: true

#       - name: Trigger APIsec scan
#         id: scan
#         uses: apisec-inc/apisec-run-scan@v1.0.5
#         with:
#           apisec-username: ${{ secrets.apisec_username }}
#           apisec-password: ${{ secrets.apisec_password }}
#           apisec-project: "PostmanWorkspace Team Red Panda All in One"
#           apisec-profile: "Master"
#           apisec-region: "Super_3"





# # This is a basic workflow to help you get started with Actions

# name: APIsec Playbook Scan

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!
        
#       - name: Trigger APIsec scan 
#         id: scan 
#         uses: apisec-inc/apisec-run-scan@v1.0.5
#         with: 
#           apisec-username: $❴❴ secrets.apisec_username ❵❵ 
#           apisec-password: $❴❴ secrets.apisec_password ❵❵ 
#           apisec-project:  testingapiproject
#           apisec-profile:  Master
#           apisec-region:   Super_1
        
        
#       - name: APIsec Playbook Regeneration
#         uses: SyedsImran/NewDrone@v1.0.0
#         with:
#           apisec-username: $❴❴ secrets.apisec_username ❵❵ 
#           apisec-password: $❴❴ secrets.apisec_password ❵❵        
#           apisec-projectname: netbankingtet123
#           apisec-profile: Master
#           apisec-region: Super_1
#           sarif-result-file: sarif
#           apisec-host: "https://developer.apisec.ai"
#           apisec-email-report: true
#           apisec-report-type: RUN_SUMMARY






# # This is a basic workflow to help you get started with Actions

# name: CI


# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
# #  pull_request:
# #    branches: [ "main" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       #- uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       - name: Trigger APIsec scan
#         id: scan
#         uses: apisec-inc/apisec-run-scan@v1.0.5
#         with:
#           apisec-username: ${{ secrets.apisec_username }}
#           apisec-password: ${{ secrets.apisec_password }}
#           apisec-project: "netbanking2"
#           apisec-profile: "Master"
#           apisec-region: "Super_1"



#       - name: APIsec Playbook Regeneration
#         # You may pin to the exact commit or the version.
#         # uses: SyedsImran/NewDrone@d87c44bc8df00f0a624dd7532f8fd813248a590a
#         uses: SyedsImran/NewDrone@v1.0.0
#         with:
#           apisec-username: ${{ secrets.apisec_username }}
#           apisec-password: ${{ secrets.apisec_password }}
#           apisec-projectname: netbankingtet123
#           apisec-profile: Master
#           apisec-region: Super_1
#           sarif-result-file: sarif
#           apisec-host: "https://developer.apisec.ai"
#           apisec-email-report: true
#           apisec-report-type: RUN_SUMMARY
